#!/bin/bash
echo "!git-upload start!"
git config --global user.email sanja81000@gmail.com
git add .
read -p "Write commit here: " commit
git commit -m "$commit"
git push origin master
echo "!git-upload done!"
